pfaproject/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
# from employe import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),  # Connexion
    path('logout/', views.logout_view, name='logout'),  # Déconnexion
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('create/', views.create, name='create'),
    path('accepter/<int:id>/', views.accepter, name='accepter'),
    path('refuser/<int:id>/', views.refuser, name='refuser'),
    path('security/', views.security, name='security'),
    path('conges/settings/', views.settings, name='settings'),
    path('conges/create/', views.create_conge, name='create_conge'),
    path('modify/<int:id>/<str:model>/', views.modify, name='modify'),
    path('delete/<int:id>/<str:model>/', views.delete, name='delete'),
    path('reporting/', views.reporting, name='reporting'),
    # path('superviseur/dashboard/', views.superviseur_dashboard, name='superviseur_dashboard'),
    # path('employe/dashboard/', views.employe_dashboard, name='employe_dashboard'),
    # path('ressources_humaines/dashboard/', views.ressources_humaines_dashboard, name='ressources_humaines_dashboard'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Equipe(models.Model):
    nom = models.CharField(max_length=100, null=True)
    seuil_conges = models.IntegerField(default=5)

class Superviseur(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    equipe = models.ForeignKey(Equipe, on_delete=models.CASCADE, null=True)

class Employe(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    solde_conge = models.IntegerField(default=0)
    superviseur = models.ForeignKey(Superviseur, on_delete=models.CASCADE)
    equipe = models.ForeignKey(Equipe, on_delete=models.CASCADE, null=True)
class RessourcesHumaines(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class TypeConge(models.Model):
    nom = models.CharField(max_length=200)
    def __str__(self):
        return self.nom

class DemandeConge(models.Model):
    employe = models.ForeignKey(Employe, related_name='demandes_conge', on_delete=models.CASCADE)
    date_debut = models.DateField()
    date_fin = models.DateField()
    type_conge = models.ForeignKey(TypeConge, on_delete=models.CASCADE)
    raison = models.TextField()
    ETAT_CHOICES = [
        ('EN_ATTENTE', 'En attente'),
        ('APPROUVEE', 'Approuvée'),
        ('REFUSEE', 'Refusée'),
    ]
    etat = models.CharField(max_length=10, choices=ETAT_CHOICES, default='EN_ATTENTE')
    def approuver(self):
     if self.etat != 'APPROUVEE':
        duree_conge = self.duree()
        if self.employe.solde_conge < duree_conge:
            raise ValueError(f"L'employé {self.employe.user.first_name} {self.employe.user.last_name} n'a pas suffisamment de jours de congé disponibles.")
        elif DemandeConge.objects.filter(employe__equipe=self.employe.equipe, date_debut__lte=self.date_fin, date_fin__gte=self.date_debut, etat='APPROUVEE').count() >= self.employe.equipe.seuil_conges:
            raise ValueError(f"Le nombre maximum de congés simultanés pour l'équipe {self.employe.equipe.nom} a été atteint.")
        else:
            self.etat = 'APPROUVEE'
            self.employe.solde_conge -= duree_conge
            self.employe.save()
            self.save()
    def duree(self):
        return (self.date_fin - self.date_debut).days + 1

users/forms.py
from django.core.exceptions import ValidationError
from django.utils import timezone
from django import forms
from .models import DemandeConge, TypeConge, Equipe
from django.contrib.auth.forms import PasswordChangeForm as AuthPasswordChangeForm

class PasswordChangeForm(AuthPasswordChangeForm):
    old_password = forms.CharField(label='Mot de passe actuel', widget=forms.PasswordInput)
    new_password1 = forms.CharField(label='Nouveau mot de passe', widget=forms.PasswordInput)
    new_password2 = forms.CharField(label='Vérification du mot de passe', widget=forms.PasswordInput)


class DemandeCongeForm(forms.ModelForm):
    class Meta:
        model = DemandeConge
        fields = ['date_debut', 'date_fin', 'type_conge', 'raison']
        widgets = {
            'date_debut': forms.DateInput(attrs={'type': 'date'}),
            'date_fin': forms.DateInput(attrs={'type': 'date'}),
            'type_conge': forms.Select(choices=TypeConge.objects.all()),
            'raison': forms.Textarea,
        }

    def clean(self):
        cleaned_data = super().clean()
        date_debut = cleaned_data.get('date_debut')
        date_fin = cleaned_data.get('date_fin')

        if date_fin and date_debut and date_fin < date_debut:
            raise ValidationError("La date de fin doit être après la date de début.")

        if date_debut and date_debut < timezone.now().date():
            raise ValidationError("La demande de congé doit être pour des dates futures.")

        return cleaned_data
    


class TypeCongeForm(forms.ModelForm):
    class Meta:
        model = TypeConge
        fields = ['nom']
        labels = {
            'nom': 'Nom du type de congé',
        }

class EquipeForm(forms.ModelForm):
    class Meta:
        model = Equipe
        fields = ['nom', 'seuil_conges']
        labels = {
            'nom': 'Nom de l\'équipe',
            'seuil_conges': 'Seuil de congés',
        }

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from .models import Superviseur, Employe, RessourcesHumaines, DemandeConge, TypeConge, Equipe
from django.http import HttpResponse
from .forms import DemandeCongeForm, TypeCongeForm, EquipeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.db.models import Count
from django.db.models import Avg, Sum
from django.core.mail import send_mail
from django.conf import settings as django_settings
from django.core.paginator import Paginator
from django.db.models import F


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('dashboard')
        else:
            return render(request, 'users/login.html', {'form': form})
    else:
        if request.user.is_authenticated:
            return redirect('dashboard')
        form = AuthenticationForm()
        return render(request, 'users/login.html', {'form': form})
    
def logout_view(request):
    logout(request)
    return redirect('login')
@login_required
def dashboard_view(request):
        if Superviseur.objects.filter(user=request.user).exists():
            return superviseur_index(request)
        elif Employe.objects.filter(user=request.user).exists():
            return employe_index(request)
        elif RessourcesHumaines.objects.filter(user=request.user).exists():
            return ressourceshumaines_index(request)
        else:
            return redirect('admin:index')


def employe_index(request):
    employe = Employe.objects.get(user=request.user)
    demandes_conge = DemandeConge.objects.filter(employe=employe)

    paginator = Paginator(demandes_conge, 5)

    page_number = request.GET.get('page')

    demandes_conge_page = paginator.get_page(page_number)
    nombre_demandes_conge = paginator.count
    context = {
        'employe': employe,
        'demandes_conge': demandes_conge_page,
        'nombre_demandes_conge': nombre_demandes_conge,
    }
    return render(request, 'employes/index.html', context)

def superviseur_index(request):
    superviseur = Superviseur.objects.get(user=request.user)
    employes = Employe.objects.filter(superviseur=superviseur)
    
    demandes_conge_en_attente = DemandeConge.objects.filter(employe__in=employes, etat='EN_ATTENTE')
    demandes_conge_approuvees = DemandeConge.objects.filter(employe__in=employes, etat='APPROUVEE')
    demandes_conge_refusees = DemandeConge.objects.filter(employe__in=employes, etat='REFUSEE')

    paginator = Paginator(demandes_conge_en_attente, 5)  
    page_number = request.GET.get('page_attente')
    demandes_conge_en_attente = paginator.get_page(page_number)
    nombre_demandes_conge_en_attente = paginator.count

    paginator = Paginator(demandes_conge_approuvees, 5)  
    page_number = request.GET.get('page_approuvees')
    demandes_conge_approuvees = paginator.get_page(page_number)
    nombre_demandes_conge_approuvees = paginator.count

    paginator = Paginator(demandes_conge_refusees, 5)  
    page_number = request.GET.get('page_refusees')
    demandes_conge_refusees = paginator.get_page(page_number)
    nombre_demandes_conge_refusees = paginator.count

    context = {
        'superviseur': superviseur,
        'employes': employes,
        'demandes_conge_en_attente': demandes_conge_en_attente,
        'demandes_conge_approuvees': demandes_conge_approuvees,
        'demandes_conge_refusees': demandes_conge_refusees,
        'nombre_demandes_conge_approuvees': nombre_demandes_conge_approuvees,
        'nombre_demandes_conge_en_attente': nombre_demandes_conge_en_attente,
        'nombre_demandes_conge_refusees': nombre_demandes_conge_refusees,
    }
    return render(request, 'superviseurs/index.html', context)

# def ressourceshumaines_index(request):
#     ressourceshumaines = RessourcesHumaines.objects.get(user=request.user)
#     employes = Employe.objects.all()
#     demandes_conge_en_attente = DemandeConge.objects.filter(etat='EN_ATTENTE')
#     demandes_conge_approuvees = DemandeConge.objects.filter(etat='APPROUVEE')
#     demandes_conge_refusees = DemandeConge.objects.filter(etat='REFUSEE')
#     context = {
#         'ressourceshumaines': ressourceshumaines,
#         'employes': employes,
#         'demandes_conge_en_attente': demandes_conge_en_attente,
#         'demandes_conge_approuvees': demandes_conge_approuvees,
#         'demandes_conge_refusees': demandes_conge_refusees,
#     }
#     return render(request, 'ressourceshumaines/index.html', context)

from django.core.paginator import Paginator

def ressourceshumaines_index(request):
    ressourceshumaines = RessourcesHumaines.objects.get(user=request.user)

    paginator_employes = Paginator(Employe.objects.all(), 5)
    paginator_en_attente = Paginator(DemandeConge.objects.filter(etat='EN_ATTENTE'), 5)
    paginator_approuvees = Paginator(DemandeConge.objects.filter(etat='APPROUVEE'), 5)
    paginator_refusees = Paginator(DemandeConge.objects.filter(etat='REFUSEE'), 5)

    page_number_employes = request.GET.get('page_employes')
    page_number_en_attente = request.GET.get('page_en_attente')
    page_number_approuvees = request.GET.get('page_approuvees')
    page_number_refusees = request.GET.get('page_refusees')

    employes_page = paginator_employes.get_page(page_number_employes)
    en_attente_page = paginator_en_attente.get_page(page_number_en_attente)
    approuvees_page = paginator_approuvees.get_page(page_number_approuvees)
    refusees_page = paginator_refusees.get_page(page_number_refusees)

    nombre_demandes_conge_en_attente = DemandeConge.objects.filter(etat='EN_ATTENTE').count()
    nombre_demandes_conge_approuvees = DemandeConge.objects.filter(etat='APPROUVEE').count()
    nombre_demandes_conge_refusees = DemandeConge.objects.filter(etat='REFUSEE').count()

    context = {
        'ressourceshumaines': ressourceshumaines,
        'employes': employes_page,
        'demandes_conge_en_attente': en_attente_page,
        'demandes_conge_approuvees': approuvees_page,
        'demandes_conge_refusees': refusees_page,
        'nombre_demandes_conge_en_attente': nombre_demandes_conge_en_attente,
        'nombre_demandes_conge_approuvees': nombre_demandes_conge_approuvees,
        'nombre_demandes_conge_refusees': nombre_demandes_conge_refusees,
    }
    return render(request, 'ressourceshumaines/index.html', context)

@login_required   
def accepter(request, id):
    demande = get_object_or_404(DemandeConge, id=id)
    try:
        demande.approuver()
        envoyer_notification_email(demande)
    except ValueError as e:
        messages.error(request, str(e))

    return redirect('dashboard')
@login_required   
def refuser(request, id):
    demande = get_object_or_404(DemandeConge, id=id)
    demande.etat = 'REFUSEE'
    envoyer_notification_email(demande)
    demande.save()
    return redirect('dashboard')



@login_required
def security(request):
    if Superviseur.objects.filter(user=request.user).exists():
        return security_superviseur(request)
    if RessourcesHumaines.objects.filter(user=request.user).exists():
        return security_ressourceshumaines(request)
    else:
        return security_employe(request)
def security_superviseur(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user) 
            return redirect('dashboard')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'superviseurs/security.html', {'form': form})

def security_employe(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user) 
            return redirect('dashboard')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'employes/security.html', {'form': form})

def security_ressourceshumaines(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user) 
            return redirect('dashboard')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'ressourceshumaines/security.html', {'form': form})

@login_required   
def create(request):
    if request.method == 'POST':
        form = DemandeCongeForm(request.POST)
        if form.is_valid():
            demande = form.save(commit=False)
            demande.employe = Employe.objects.get(user=request.user)
            if DemandeConge.objects.filter(employe=demande.employe, date_debut__lte=demande.date_fin, date_fin__gte=demande.date_debut).exists():
                form.add_error(None, "Une demande de congé pour les mêmes dates existe déjà.")
            elif demande.duree() > demande.employe.solde_conge:
                form.add_error(None, "La durée de la demande de congé est supérieure à votre solde de congé.")
            else:
                demande.save()
                envoyer_notification_email_superviseur(demande)
                return redirect('dashboard')
    else:
        form = DemandeCongeForm()
    return render(request, 'employes/create.html', {'form': form})



def envoyer_notification_email_superviseur(demande):
    # Configuration de l'API Sendinblue
    configuration = Configuration()

users/templates/employes/create.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Créer une demande de stage</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <h2>Créer une demande de stage</h2>
    <a href="{% url 'dashboard' %}">Retour</a>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Envoyer</button>
    </form>

</body>
</html>

users/templates/employes/index.html
{% extends "base.html" %}

{% block title %}Employe{% endblock %}

{% block topbar-left-container %}
<div class="tb-title"><i class="fa-solid fa-user"></i> Espace Employé : <span class="tp-content">{{ user.first_name }} {{ user.last_name }}</span></div>
<div class="tb-title">/</div>
<div class="tb-title"><i class="fa-solid fa-user-group"></i> Equipe : <span class="tp-content">{{ employe.equipe.nom }}</span></div>

{% endblock %}

{% block topbar-right-container %}
<a class="security-button" href="{% url 'security' %}"><i class="fa-solid fa-lock"></i> Securité</a>
<a class="logout-button" href="{% url 'logout' %}"><i class="fa-solid fa-right-from-bracket"></i> Déconnexion</a>
{% endblock %}

{% block content %}
    <p> Votre solde de congé est de <span class="nbr">{{employe.solde_conge}}</span> jours</p>
    <p>Vous avez <span class="nbr">{{nombre_demandes_conge}}</span> demande(s) de congé</p>
    <div class="actions">
        {% if employe.solde_conge > 0 %}
        <a href="{% url 'create' %}"><i class="fa-solid fa-plus"></i> Créer une demande de congé</a>
        {% else %}
        <p class="plus_conge">Vous n'avez plus de jours de congé disponibles.</p>
        {% endif %}
    </div>
    <h3>Vos demandes de congé</h3>
    <table>
        <thead>
            <tr>
                <th>Debut</th>
                <th>Fin</th>
                <th>Durée (jours)</th>
                <th>Type</th>
                <th>Raison</th>
                <th>Etat</th>
            </tr>
        </thead>
        <tbody>
            {% for demande in demandes_conge %}
            <tr>
                <td>{{ demande.date_debut }}</td>
                <td>{{ demande.date_fin }}</td>
                <td>{{ demande.duree }}</td>
                <td>{{ demande.type_conge.nom }}</td>
                <td>{{ demande.raison }}</td>
                <td>{{ demande.get_etat_display }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5">Vous n'avez pas de demande de congé.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if demandes_conge.has_previous %}
                <a href="?page=1">&laquo; première</a>
                <a href="?page={{ demandes_conge.previous_page_number }}">&laquo; précédente</a>
            {% endif %}

            <span class="current">
                Page {{ demandes_conge.number }} sur {{ demandes_conge.paginator.num_pages }}.
            </span>

            {% if demandes_conge.has_next %}
                <a href="?page={{ demandes_conge.next_page_number }}">suivante &raquo;</a>
                <a href="?page={{ demandes_conge.paginator.num_pages }}">dernière &raquo;</a>
            {% endif %}
        </span>
    </div>

{% endblock %}

users/templates/employes/security.html
{% extends "base.html" %}

{% block title %}Employe{% endblock %}

{% block topbar-left-container %}
<div class="tb-title"><i class="fa-solid fa-user"></i> Espace Employe : <span class="tp-content">{{ user.first_name }} {{ user.last_name }}</span></div>
<div class="tb-title">/</div>
<div class="tb-title"><i class="fa-solid fa-user-group"></i> Equipe : <span class="tp-content">{{ user.employe.equipe.nom }}</span></div>

{% endblock %}

{% block topbar-right-container %}
<a class="return-button" href="{% url 'dashboard' %}"><i class="fa-solid fa-arrow-rotate-left"></i> Retour</a>
<a class="security-button" href="{% url 'security' %}"><i class="fa-solid fa-lock"></i> Securité</a>
<a class="logout-button" href="{% url 'logout' %}"><i class="fa-solid fa-right-from-bracket"></i> Déconnexion</a>
{% endblock %}

{% block content %}
<h2>Changement du mot de passe</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Changer le mot de passe</button>
    </form>

{% endblock %}